id: P006956
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:32:47.186811
source_metadata:
  id: bdr:W3CN2367
  title: ཐུབ་དབང་གནས་བརྟན་བཅུ་དྲུག་གི་མཆོད་སྤྲིན།
  author: ''
  volumes:
    032692d968ca42a89a106951cbbd570b:
      image_group_id: I3CN2369
      title: Volume 1 of thub dbang gnas brtan bcu drug gi mchod sprin/
      volume_number: 1
      total_pages: 87
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
