id: P006956
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2367
  title: ཐུབ་དབང་གནས་བརྟན་བཅུ་དྲུག་གི་མཆོད་སྤྲིན།
  author: ''
  volumes:
    f1481e74956f455d9d6124025d7829f7:
      image_group_id: I3CN2369
      title: ''
      volume_number: 1
      total_pages: 87
ebook_metadata:
  title: ཐུབ་དབང་གནས་བརྟན་བཅུ་དྲུག་གི་མཆོད་སྤྲིན།
  author: ''
  sku: P006956
  cover: cover.jpg
  layers:
  - pagination
