id: opecha:P006956
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2367
  title: ཐུབ་དབང་གནས་བརྟན་བཅུ་དྲུག་གི་མཆོད་སྤྲིན།
  volume:
    032692d968ca42a89a106951cbbd570b:
      image_group_id: I3CN2369
      title: Volume 1 of thub dbang gnas brtan bcu drug gi mchod sprin/
      volume_number: 1
      total_pages: 87
  author: ''
ebook_metadata:
  title: ཐུབ་དབང་གནས་བརྟན་བཅུ་དྲུག་གི་མཆོད་སྤྲིན།
  author: ''
  sku: P006956
  cover: cover.jpg
  layers:
  - pagination
