id: IB8744B0E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T03:01:40+00:00'
last_modified: '2022-06-08T12:56:29.179132+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2367
  title: ཐུབ་དབང་གནས་བརྟན་བཅུ་དྲུག་གི་མཆོད་སྤྲིན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A6EE:
      image_group_id: I3CN2369
      title: Volume 1 of thub dbang gnas brtan bcu drug gi mchod sprin/
      total_pages: 87
      order: 1
      base_file: A6EE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
