id: IB8744B0E
legacy_id: P006956
ocr_import_info:
  bdrc_scan_id: W3CN2367
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T03:01:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:06:53.652389+00:00'
last_modified: 2022-09-03 21:06:59.667141
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN2367
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN2367
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐུབ་དབང་གནས་བརྟན་བཅུ་དྲུག་གི་མཆོད་སྤྲིན།
statistics:
  ocr_word_mean_confidence_index: 0.5825366571387194
  ocr_word_median_confidence_index: 0.5699999928474426
quality: null
bases:
  I3CN2369:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2369
      total_pages: 87
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN2369.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5825366571387194
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
